name: Update Checker

env:
  REPO_OWNER: unifreq
  REPO_NAME: openwrt_packit
  REPO_BRANCH: master
  
on:
  workflow_dispatch:
    inputs:
      update:
        description: 'Force update'
        required: false
        default: 'false'
        
  schedule:
    - cron: 0 0/1 * * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Get Commit Hash
      id: getHash
      run: |
        commitHash=$(curl  "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/git/refs/heads/${REPO_BRANCH}" | jq '.object.sha')
        echo "::set-output name=commitHash::$commitHash"
        
    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v2
      with:
        path: .commitHash
        key: HEAD-${{ steps.getHash.outputs.commitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash
    - name: Trigger build
      if: steps.cacheHash.outputs.cache-hit != 'true' || (github.event.inputs.update == 'true' && github.event.inputs.update  != 'false') 
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: Source Code Update

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
