# This is a basic workflow to help you get started with Actions

name: Update form flippy

on:
  repository_dispatch:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update files
        run: |
          rm -rf opt/openwrt
          git clone --depth=1 https://github.com/unifreq/openwrt_packit.git
          mv openwrt_packit opt/openwrt
          rm -rf opt/openwr/.git
          rm -rf opt/openwr/.gitignore
          
      - name: GitHub Commit & Push
        uses: actions-js/push@v1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          message: update package script from upstream
          


